coverage_service: cobertura_xml
xcworkspace: Example/PopoverObjC.xcworkspace
xcodeproj: Example/PopoverObjC.xcodeproj
scheme: PopoverObjC-Example
configuration: TestedConfiguration
source_directory: Example/
output_directory: Example/
ignore: