
osx_image: xcode9
language: objective-c

cache: cocoapods
podfile: Example/Podfile

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - WORKSPACE_NAME=`sudo find ./ -name "*.xcworkspace" -type f |while read var; do echo $(basename $var .xcworkspace); done`
    # the file named '*.xcworkspace' should be created by 'pod lib create...'

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - pod install --project-directory=Example

script:
  - set -o pipefail
  - echo $WORKSPACE_NAME
  #- xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -configuration Debug clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
  #- xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -configuration Release clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
  #- pod lib lint --allow-warnings --verbose
  - xcodebuild -workspace Example/$WORKSPACE_NAME.xcworkspace -scheme $WORKSPACE_NAME-Example \
  -destination 'platform=iOS Simulator,OS=11.0,name=iPhone 8' \
  -destination 'platform=iOS Simulator,OS=8.3,name=iPhone 6' \
  -destination 'platform=iOS Simulator,OS=9.3,name=iPhone 6s' \
  -destination 'platform=iOS Simulator,OS=10.3,name=iPhone 7' \
  test

  - pod lib lint --allow-warnings --verbose

after_success:
  - sleep 3
